config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :applicants
  resources :funds
  resources :payments, only: [:index]
  resources :projects

  root 'applicants#index'
end

app/models/applicant.rb
# frozen_string_literal: true

# Applications to Projects
class Applicant < ApplicationRecord
  attribute :status, :integer, default: 0

  validates :name, presence: true, uniqueness: true
  validates :overview, presence: true
  validates :funding, numericality: true, presence: true

  belongs_to :project

  has_many :statuses, dependent: :destroy

  accepts_nested_attributes_for :statuses, reject_if: :all_blank

  def latest_status
    statuses.order(id: :desc).first.status_type
  end

  def project_title
    'Project'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fund.rb
# frozen_string_literal: true

# Funds for Projects
class Fund < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :total, numericality: { only_integer: true }

  has_many :projects, inverse_of: :fund, dependent: :restrict_with_error
end

app/models/project.rb
# frozen_string_literal: true

# Projects for Funds and Applicants to apply for funding for
class Project < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :payment_date, presence: true

  belongs_to :fund

  def sorted_payments
    payments.sort_by(&:date)
  end

  def applicants_for_project
    applicants = applicants.select do |applicant|
      if applicant.project.title == title
        true
      else
        false
      end
    end
    applicants.map(&:name).join(', ')
  end

end

app/models/status.rb
class Status < ApplicationRecord
  validates :comment, presence: true
  enum status_type: { applied: 0, initial_review: 1, more_information_required: 2, declined: 3, approved: 4 }
  belongs_to :applicant
end

app/controllers/applicants_controller.rb
# frozen_string_literal: true

# Controller for CRUD management of Applicants
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: %i[show edit update destroy]

  # GET /applicants
  def index
    @applicants = Applicant.order(:name)
  end

  # GET /applicants/1
  def show; end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit; end

  # POST /applicants
  def create
    @applicant = Applicant.new(applicant_params)
    @status = Status.create(status_type: 'applied', comment: 'New applicant', applicant: @applicant)

    if @applicant.save
      redirect_to @applicant, notice: 'Applicant was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /applicants/1
  def update
    if @applicant.update(applicant_params)
      redirect_to @applicant, notice: 'Applicant was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /applicants/1
  def destroy
    @applicant.destroy
    redirect_to applicants_url, notice: 'Applicant was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_applicant
    @applicant = Applicant.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def applicant_params
    params.require(:applicant).permit(:name, :overview, :funding, :project_id, statuses_attributes: [:status_type, :comment])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/funds_controller.rb
# frozen_string_literal: true

# Controller for CRUD management of Funds
class FundsController < ApplicationController
  before_action :set_fund, only: %i[show edit update destroy]

  # GET /funds
  def index
    @funds = Fund.order(:title)
  end

  # GET /funds/1
  def show; end

  # GET /funds/new
  def new
    @fund = Fund.new
  end

  # GET /funds/1/edit
  def edit; end

  # POST /funds
  def create
    @fund = Fund.new(fund_params)

    if @fund.save
      redirect_to @fund, notice: 'Fund was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /funds/1
  def update
    if @fund.update(fund_params)
      redirect_to @fund, notice: 'Fund was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /funds/1
  def destroy
    @fund.destroy
    redirect_to funds_url, notice: 'Fund was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_fund
    @fund = Fund.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def fund_params
    params.require(:fund).permit(:title, :total)
  end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

# Controller for upcoming Payments
class PaymentsController < ApplicationController
  def index; end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# Controller for CRUD management of Projects
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  # GET /projects
  def index
    @projects = Project.order(:title)
  end

  # GET /projects/1
  def show; end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:title, :fund_id, :payment_date)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper
module ApplicationHelper
end

app/helpers/funds_helper.rb
# frozen_string_literal: true

# Helpers for Funds
module FundsHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

# Helpers for Projects
module ProjectsHelper
end

app/views/applicants/_applicant.html.erb
<div id="<%= dom_id applicant %>">
  <p>
    <strong>Name:</strong>
    <%= applicant.name %>
  </p>

  <p>
    <strong>Overview:</strong>
    <%= applicant.overview %>
  </p>

  <p>
    <strong>Funding:</strong>
    <%= applicant.funding %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= applicant.project.title %>
  </p>

  <p>
    <strong>Status Updates:</strong>
  </p>

  <table id="applicants">
    <thead>
      <tr>
        <th>Date</th>
        <th>Status</th>
        <th>Comment</th>
      </tr>
    </thead>
    <tbody>
    <% applicant.statuses.each do |status| %>
      <tr>
        <td><%= status.created_at %></td>
        <td><%= status.status_type.titleize %></td>
        <td><%= status.comment %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>

app/views/applicants/_form.html.erb
<%= form_with(model: applicant) do |form| %>
  <% if applicant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
        <% applicant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :overview, style: "display: block" %>
    <%= form.text_area :overview %>
  </div>

  <div>
    <%= form.label :funding, style: "display: block" %>
    <%= form.number_field :funding %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.collection_select :project_id, Project.order(:name), :id, :title %>
  </div>

  <% unless applicant.new_record? %>
    <div>
      <%= form.fields_for :statuses, @applicant.statuses.build do |status_form| %> 
        <%= status_form.label :status, style: "display: block" %>
        <%=
          status_form.select :status_type, options_for_select(
            Status.status_types.map { |k, v| [k.titleize, Status.status_types.key(v)] }, applicant.latest_status || 0
          )
        %>
        <%= status_form.label :comment, style: "display: block" %>
        <%= status_form.text_field :comment %>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing applicant</h1>

<%= render "form", applicant: @applicant %>

<br>

<div>
  <%= link_to "Show this applicant", @applicant %> |
  <%= link_to "Back to applicants", applicants_path %>
</div>

app/views/applicants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Applicants</h1>

<p>
  <%= link_to "New applicant", new_applicant_path %>
</p>

<table id="applicants">
  <thead>
    <tr>
      <th>Name</th>
      <th>Project</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @applicants.each do |applicant| %>
    <tr>
      <td><%= applicant.name %></td>
      <td><%= applicant.project_title %></td>
      <td><%= applicant.latest_status.titleize %></td>
      <td><%= link_to "Show this applicant", applicant %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/applicants/new.html.erb
<h1>New applicant</h1>

<%= render "form", applicant: @applicant %>

<br>

<div>
  <%= link_to "Back to applicants", applicants_path %>
</div>

app/views/applicants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @applicant %>

<div>
  <%= link_to "Edit this applicant", edit_applicant_path(@applicant) %> |
  <%= link_to "Back to applicants", applicants_path %>

  <%= button_to "Destroy this applicant", @applicant, method: :delete %>
</div>

app/views/funds/_form.html.erb
<%= form_with(model: fund) do |form| %>
  <% if fund.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fund.errors.count, "error") %> prohibited this fund from being saved:</h2>

      <ul>
        <% fund.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.number_field :total %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/funds/_fund.html.erb
<div id="<%= dom_id fund %>">
  <p>
    <strong>Title:</strong>
    <%= fund.title %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= fund.total %>
  </p>

</div>

app/views/funds/edit.html.erb
<h1>Editing fund</h1>

<%= render "form", fund: @fund %>

<br>

<div>
  <%= link_to "Show this fund", @fund %> |
  <%= link_to "Back to funds", funds_path %>
</div>

app/views/funds/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Funds</h1>

<p><%= link_to "New fund", new_fund_path %></p>

<table id="funds">
  <thead>
    <tr>
      <th>Title</th>
      <th>Total</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @funds.each do |fund| %>
    <tr>
      <td><%= fund.title %></td>
      <td><%= fund.total %></td>
      <td><%= link_to "Show this fund", fund %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/funds/new.html.erb
<h1>New fund</h1>

<%= render "form", fund: @fund %>

<br>

<div>
  <%= link_to "Back to funds", funds_path %>
</div>

app/views/funds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fund %>

<div>
  <%= link_to "Edit this fund", edit_fund_path(@fund) %> |
  <%= link_to "Back to funds", funds_path %>

  <%= button_to "Destroy this fund", @fund, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChangeX App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav>
      <strong>
        <%= link_to "Applicants", applicants_path %>
        |
        <%= link_to "Funds", funds_path %>
        |
        <%= link_to "Payments", payments_path %>
        |
        <%= link_to "Projects", projects_path %>
      </strong>
    </nav>

    <hr>

    <%= yield %>
  </body>
</html>

app/views/payments/index.html.erb
<h1>Payments</h1>

<%
  projects = Project.all

  dates = projects.each_with_object(Hash.new { |k, v| k[v] = [] }) do |project, output|
    output[project.payment_date] << project.title
  end
%>

<table id="payments">
  <thead>
    <tr>
      <th>Date</th>
      <th>Project</th>
      <th>Payments due</th>
    </tr>
  </thead>
  <tbody>
  <%
    dates.sort_by { |date, _project| date }
         .select { |date, _project| date >= Date.current }
         .to_h
         .keys
         .each do |date|
  %>
    <% dates[date].each do |project| %>
      <tr>
        <td><%= date %></td>
        <td><%= project %></td>
        <td>
          <%=
            project = Project.find_by(title: project)
            applicants = Applicant.all.select do |applicant|
              if applicant.project.title == project.title &&
                 applicant.latest_status == 'approved'
                true
              else
                false
              end
            end

            applicants.map(&:name).join(', ')
           %>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :fund_id, style: "display: block" %>
    <%= form.collection_select :fund_id, Fund.order(:name), :id, :title %>
  </div>

  <div>
    <%= form.label :payment_date, style: "display: block" %>
    <%= form.date_field :payment_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Fund:</strong>
    <%= project.fund.title %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<p><%= link_to "New project", new_project_path %></p>

<table id="funds">
  <thead>
    <tr>
      <th>Title</th>
      <th>Fund</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.title %></td>
      <td><%= project.fund.title %></td>
      <td><%= link_to "Show this project", project %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>